import keyMirror from 'keymirror'

export var ActionTypes = keyMirror({
  GET_REPORT_SUCCESS: null,
  GET_REPORT: null,
  GET_RESIGNDATES_SUCCESS: null,
  GET_RESIGNDATES: null,
  GET_RESIGNDATESLOOKUP_SUCCESS: null,
  GET_RESIGNDATESLOOKUP: null,
  HANDLE_RESIGNDATES: null,
  // CREATEREPORT_SUCCESS: null,
  //  CREATEREPORT: null,
  HANDLE_CREATEREPORT: null,
  HANDLE_REPORT: null,
  HANDLE_SELECTEDDESTINATION: null,
  HANDLE_SELECTEDRESIGNDATES: null,
  HANDLE_DESTINATION_FIELD: null,
  HANDLE_SEASON_FIELD: null,
  HANDLE_CHANGE_FIELD: null,
  HANDLE_SELECTEDYEAR: null,
  HANDLE_YEAR_FIELD: null,
})