import keyMirror from 'keymirror'

export var ActionTypes = keyMirror({
  GET_MISSINGMANAGERCOMMENTSAPPLICATION_SUCCESS: null,
  GET_MISSINGMANAGERCOMMENTSAPPLICATION: null,
  HANDLE_MISSINGMANAGERCOMMENTSAPPLICATION: null
  //HANDLE_POSTMODAL:null,
})
 