import keyMirror from 'keymirror'

export var ActionTypes = keyMirror({
  GET_ALLAPPLICATION_SUCCESS: null,
  GET_ALLAPPLICATION: null,
  HANDLE_ALLAPPLICATION: null,
  GET_PLANTORESIGNAPPLICATION_SUCCESS: null,
  GET_PLANTORESIGNAPPLICATION: null,
  HANDLE_PLANTORESIGNAPPLICATION: null,
  GET_MISSINGMANAGERCOMMENTSAPPLICATION_SUCCESS: null,
  GET_MISSINGMANAGERCOMMENTSAPPLICATION: null,
  HANDLE_MISSINGMANAGERCOMMENTSAPPLICATION: null,
  GET_MISSINGAPPLICATION_SUCCESS: null,
  GET_MISSINGAPPLICATION: null,
  HANDLE_MISSINGAPPLICATION: null
  
  
 

})
 