import keyMirror from 'keymirror';

export var ActionTypes = keyMirror({
    GET_AVAILABLEPOSITIONS_SUCCESS: null,
    GET_AVAILABLEPOSITIONS: null,
    GET_POSITIONASSIGNS_SUCCESS: null,
    GET_POSITIONASSIGNS: null,
    GET_STAFF_SUCCESS: null,
    GET_STAFF: null,
    GET_SEASONGEOGRAPHY_SUCCESS: null,
    GET_SEASONGEOGRAPHY: null,
    HANDLE_STAFF_FIELD: null,
    HANDLE_CURRENTPOSITIONASSIGN_FIELD: null,
    HANDLE_NEXTPOSITIONASSIGN_FIELD: null,
    HANDLE_FOLLOWINGPOSITIONASSIGN_FIELD: null,
    HANDLE_NEXTFOLLOWINGPOSITIONASSIGN_FIELD: null
});